### ISSUE TITLE
Day forecast test truncation

### ISSUE THREAD

**Issue by ScottChapman** [n0bel/PiClock#108]
Many of the day forecast text appears to be truncated. It would be really good to have the text wrap.

I realize this would likely require a fairly UI change. Perhaps you could do:
```
---------------------------------
| Thursday            70% 54/32 |
| Mostly cloudy with periods    |
| of rain throughout day.       |
---------------------------------
```

That way it is still 3-lines of text per day

**Comment by n0bel** [comment]
I've seen it, but I haven't decided what the right answer is.   It didn't seem (to me) that the additional information was more useful.    For me I find the numeric version of the forecast more meaningful, since it shows Rain or Snow % and amounts.    So things won't always fit on 3 lines either.   A solution may be to make the whole box one big wrapped text box.    Then we loose the nice formatting.    Notice my forecast for Wednesday, it won't fit on 3 lines either:
![image](https://user-images.githubusercontent.com/9255390/50357775-bc6d1780-051c-11e9-940f-fe5df2ec7322.png)

**Comment by n0bel** [comment]
Formatting changed on commit:  f191cf7b8d13123392cfec66e75026b98484c0af
Its still not ideal, but I think the best at this point.

**Comment by ScottChapman** [comment]
Yea, looks better. But there is some overlap now. Not sure, but perhaps you can reduce the gap between the top three lines?
![img_20181230_153137](https://user-images.githubusercontent.com/1517892/50567298-5600aa00-0d11-11e9-915e-b3e8f14e13c5.jpg)

**Comment by n0bel** [comment]
nomatter what choice is made, there will be overlap, or the text will be too small for the short things.
A font size change may be the next choice.
