### ISSUE TITLE
Date format 

### ISSUE THREAD

**Issue by djevrek** [n0bel/PiClock#15]
How can i configure date format thats on top of page ? I want it to be something like this ... "monday 1. january 2015."

**Comment by n0bel** [comment]
Line 95 in PyQtPiClock.py:

ds = "{0:%A} {0.day}.{0:%B} {0.year}".format(now,sup).lower()

For reference look at http://strftime.org/ for python date options, and https://docs.python.org/2/library/string.html (section 7.1.3) .

I added .lower() because your example was all lower case.

it could be just:  ds = "{0:%A} {0.day}.{0:%B} {0.year}".format(now,sup)

**Comment by djevrek** [comment]
Working, thanks
