### ISSUE TITLE
Elongated Clock Face Solved

### ISSUE THREAD

**Issue by gshafer** [n0bel/PiClock#39]
Just an FYI, I found a fix for the 800x480 issue that causes an elongated clock face.

I was actually looking for something else and stumbled across this info.

I added the following code to /boot/config.txt 

`#Added to try and use 800x480 screen
# uncomment to force a specific HDMI mode (here we are forcing 800x480!)

hdmi_group=2
hdmi_mode=1
hdmi_mode=87
hdmi_cvt=800 480 60 6 0 0 0

max_usb_current=1
# End of added code`

Then reboot the RP. 

Screen now looks like:

![img_0042](https://cloud.githubusercontent.com/assets/203958/18994336/5d86ab34-86f5-11e6-90d9-c6e2a871f127.JPG)

Thought it might fix the issue on your clock also without having to get a new screen.

**Comment by n0bel** [comment]
YAY! WOW.. I totally forgot that hdmi things have multiple modes.  I've always (stupidly) let the defaults work, figuring that I'd get the best resolution.  

My work around was a little easier. 

I used this: http://elinux.org/RPiconfig (the hdmi_group and hdmi_mode section) plus this: https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=24679 (focusing more on the tvservice command)

Playing around with tvservice -m CEA and tvservice -m DMT and tvservice -e .... commands to see what the display could do, I came up with:
```
hdmi_group=1
hdmi_mode=4
```

![20161001_142355](https://cloud.githubusercontent.com/assets/9255390/19016603/66a7fbf6-87e4-11e6-84c8-0633d977b8ab.jpg)

YAY!

It is worth noting that the HDMI controller of the LCD is mapping the specified resolution onto the native resolution of the display.   I have since found that my display's physical resolution is 720x576, which is 5:4, however I picked 1280x720 as a forced mode because it is 16:9 and seemed to look the best.
