### ISSUE TITLE
customizing frontend

### ISSUE THREAD

**Issue by nightflasher** [n0bel/PiClock#51]
as in my first reported issue said, i'm using my kedei 3.5" (semi-) spi lcd and as you know, the 3.5" isn't a big screen, but it is perfect for this project as i like to use it mobile (like in the car). but now i ran into this little problem: too many wheather information on the right and many other informations are too small to read...how can "we" change the skin of the frontend to cover more screen sizes?

**Comment by n0bel** [comment]
Font sizes are made relative to the screen resolution, so that they fit in their boxes.   If you can't read them you'll probably have to make the boxes bigger too, or they'll just run out of room.

The font sizes are set in code like this:
```
              "; background-color: transparent; font-size: " +
                     str(int(50 * xscale)) + "px; " +
                     Config.fontattr +
"}")
```

Which is inside setStyleSheet calls.

As you point out there is probably too much info on the right side for a small screen as well.

The entire layout is directly coded.   There is no easy skinning framework at this time.  I'm not sure I have a good answer for you except to do some recodeing.
